importScript("common/commonLibraries/sentry.4.5.3.js")
importScript("common/commonLibraries/amplitude-4.5.2.js")
importScript("common/commonLibraries/ga.js")
importScript("background/backgroundLibraries/firebase.js")
importScript("common/commonLibraries/eventEmitter.js")

importScript("background/backgroundConstants.js")
importScript("common/commonConstants.js")
importScript("common/commonHelpers/defaultValuesHelper.js")
importScript("background/backgroundHelpers/migrationHelper.js")
importScript("background/backgroundHelpers/trackingHelper.js")

importScript("background/backgroundHelpers/indexdbHelper.js")
importScript("background/backgroundHelpers/localstorageHelper.js")
importScript("background/backgroundHelpers/reinstall.js")

importScript("background/backgroundHelpers/authHelper.js")
importScript("background/backgroundHelpers/dateHelper.js")
importScript("background/backgroundHelpers/deviceHelper.js")
importScript("background/backgroundHelpers/firestoreHelper.js")
importScript("background/backgroundHelpers/messageHelper.js")
importScript("background/backgroundHelpers/appDataHelper.js")
importScript("common/commonHelpers/utility.js")

importScript("background/config.js")
importScript("background/init.js")
importScript("background.js")