const COMMONCONSTANTS = {
  LICENSE_BUY_URL: "https://www.getstickynotes.com/payment?__from=apps",
  UNINSTALL_URL: "https://www.getstickynotes.com/confirm-uninstall-from-chrome",
  REVIEWS_URL:
    "https://chrome.google.com/webstore/detail/sticky-notes-just-popped/plpdjbappofmfbgdmhoaabefbobddchk/reviews",
  PROVIDER_CHECK_URL:
    "https://us-central1-ukiv-com-sticky-notes.cloudfunctions.net",
  VIDEO_URL:
    "https://www.getstickynotes.com/frequently-asked-questions-faqs?__from=apps", //This is also hardcoded at some places.
  PAYMENT_URL: "https://www.getstickynotes.com/payment?__from=apps", //This is also hardcoded at some places.
  HELP_URL: "https://www.getstickynotes.com/help?__from=apps", //This is also hardcoded at some places.
  EXTENSION_UPDATE_URL_C21:
    "https://www.getstickynotes.com/chrome-extension-updated-3/",
  OFFER_URL_BF20:
    "https://www.getstickynotes.com/black-friday?__offer=our_black_friday_sale", //This is also hardcoded at some places.
  OFFER_URL_SPECIAL:
    "https://getstickynotes.com/special-offer?__offer=we-are-here-with-you", //This is also hardcoded at some places.
  INSTALLED_URL:
    "https://www.getstickynotes.com/installed-on-chrome?__from=apps", //This is also hardcoded at some places.
  RATING_FROM_CHROME: "https://www.getstickynotes.com/rating-from-chrome", //This is also hardcoded at some places.

  // DYNAMIC_DATA_CALL_URL:"https://api.npoint.io/4fdc5f27bd9a8981c001",
  // Change chrome to edge to chrome
  DYNAMIC_DATA_CALL_URL:
    "https://storage.googleapis.com/ukiv-stickynotes/static/dynamic_content.json",

  LOG_SENTRY: true,
  LOG_TRACK: true,
  RELEASE_VERSION: 29,

  TOTAL_FOLDERS: 10,

  FROM_POPUP: "FROM_POPUP",
  TO_POPUP: "FROM_POPUP",
  TRIAL_DAYS: 10,
  TRIAL_COUNT: 1,
  TRIAL_NO_DISTRACTION_DAYS: -1,
  TRIAL_START_DATE: "TRIAL_START_DATE",

  LOADER_WAIT_TIME: 3000,
  DYNAMIC_DATA: "DYNAMIC_DATA",
  TOUR_SHOWN: "TOUR_SHOWN",
  USER_UNVERIFIED: "USER_UNVERIFIED",

  //Folder switcher
  FOLDER_SWITCHER_CLICK: "FOLDER_SWITCHER_CLICK",
  FOLDER_PILL_CLICK: "FOLDER_PILL_CLICK",

  //TOUR
  TOUR_NEXT_STEP: "TOUR_NEXT_STEP",
  TOUR_EXIT: "TOUR_EXIT",

  //ADS
  JSON_LOADED: "JSON_LOADED",
  JSON_ERROR: "JSON_ERROR",
  AD_SHOWN: "AD_SHOWN",
  AD_HOVER: "AD_HOVER",
  AD_CLICK: "AD_CLICK",
  JSON_CALLED: "JSON_CALLED",
  JSON_PARSE_ERROR: "JSON_PARSE_ERROR",
  DEFAULT_BANNER: "DEFAULT_BANNER",
  AD_CROSS_CLICK: "AD_CROSS_CLICK",
  PREMIUM_AD: "PREMIUM_AD",

  // Change with caution
  NOTE_PREFIX_STRING: "n",
  SETTINGS_KEY_STRING: "settings",
  FOLDER_NAMES_KEY_STRING: "folderNames",
  OPEN_TABS_IDS: "OPEN_TABS_IDS",
  SEND_TO_GA: "SEND_TO_GA",
  SEND_TO_AMPLITUDE: "SEND_TO_AMPLITUDE",
  BYTES: "BYTES",

  //sync variables
  SYNC_FIRST_INSTALL_DATA: "SYNC_FIRST_INSTALL_DATA",
  SYNC_FIRST_INSTALL_RELEASE: "SYNC_FIRST_INSTALL_RELEASE",
  SYNC_LAST_TIME_APP_OPEN_COUNT: "SYNC_LAST_TIME_APP_OPEN_COUNT",
  SYNC_TOTAL_INSTALLS: "SYNC_TOTAL_INSTALLS",
  SYNC_NO_OF_DAYS_USED: "SYNC_NO_OF_DAYS_USED",
  SYNC_CURRENT_INSTALL_DATE: "SYNC_CURRENT_INSTALL_DATE",
  SYNC_CURRENT_RELEASE: "SYNC_CURRENT_RELEASE",
  //

  INTERNAL_ACTION: "INTERNAL_ACTION",
  INSTALL_ERROR: "INSTALL_ERROR",
  INDEXDB_ERROR: "INDEXDB_ERROR",
  INSERT_TRANSACTION_ERROR: "INSERT_TRANSACTION_ERROR",
  INSTALL_ERROR1: "INSTALL_ERROR1",
  INSTALL_ERROR2: "INSTALL_ERROR2",
  INSTALL_ERROR3: "INSTALL_ERROR3",
  INSTALL_SUCCESS1: "INSTALL_SUCCESS1",
  INSTALL_SUCCESS2: "INSTALL_SUCCESS2",
  INSTALL_SUCCESS3: "INSTALL_SUCCESS3",
  INSTALL_TRY_1: "INSTALL_TRY_1",
  INSTALL_TRY_2: "INSTALL_TRY_2",
  INSTALL_TRY_3: "INSTALL_TRY_3",

  USERS_LOCAL_DATA_ROW_ID_IN_USERS_TABLE: "userLocalData",

  OPEN_POPUP: "OPEN_POPUP",
  BROADCAST_POPUP_OPENED: "BROADCAST_POPUP_OPENED",

  CLICK_EVENT: "CLICK_EVENT",
  BROADCAST_ON_CLICK_EVENT: "BROADCAST_ON_CLICK_EVENT",

  NOTES_DATA_FETCHED: "NOTES_DATA_FETCHED",
  UKIV_INDEXDB_CURRENT_VERSION: 1,

  SIGNED_IN_CHROME: "SIGNED_IN_CHROME",

  FETCH_ALL_NOTES: "FETCH_ALL_NOTES",
  FETCH_ALL_NOTES_SUCCESS: "FETCH_ALL_NOTES_SUCCESS",
  FETCH_ALL_NOTES_ERROR: "FETCH_ALL_NOTES_ERROR",

  CLEAR_ALL_NOTES_DATA: "CLEAR_ALL_NOTES_DATA",
  CLEAR_ALL_NOTES_DATA_SUCCESS: "CLEAR_ALL_NOTES_DATA_SUCCESS",
  CLEAR_ALL_NOTES_DATA_ERROR: "CLEAR_ALL_NOTES_DATA_ERROR",

  SAVE_NOTE: "SAVE_NOTE",
  SAVE_NOTE_SUCCESS: "SAVE_NOTE_SUCCESS",
  SAVE_NOTE_ERROR: "SAVE_NOTE_ERROR",

  FETCH_FOLDER_ALL_NOTES: "FETCH_FOLDER_ALL_NOTES",
  FETCH_FOLDER_ALL_NOTES_SUCCESS: "FETCH_FOLDER_ALL_NOTES_SUCCESS",
  FETCH_FOLDER_ALL_NOTES_ERROR: "FETCH_FOLDER_ALL_NOTES_ERROR",

  FETCH_NOTE: "FETCH_NOTE",
  FETCH_NOTE_SUCCESS: "FETCH_NOTE_SUCCESS",
  FETCH_NOTE_ERROR: "FETCH_NOTE_ERROR",

  FETCH_VALUES: "FETCH_VALUES",
  FETCH_VALUES_SUCCESS: "FETCH_VALUES_SUCCESS",
  FETCH_VALUES_ERROR: "FETCH_VALUES_ERROR",

  SAVE_VALUES: "SAVE_VALUES",
  SAVE_VALUES_SUCCESS: "SAVE_VALUES_SUCCESS",
  SAVE_VALUES_ERROR: "SAVE_VALUES_ERROR",

  CREATE_ACCOUNT: "CREATE_ACCOUNT",
  CREATE_ACCOUNT_SUCCESS: "CREATE_ACCOUNT_SUCCESS",
  CREATE_ACCOUNT_ERROR: "CREATE_ACCOUNT_ERROR",

  SEND_EMAILID_CONFIRMATION_EMAIL: "SEND_EMAILID_CONFIRMATION_EMAIL",
  SEND_EMAILID_CONFIRMATION_EMAIL_SUCCESS:
    "SEND_EMAILID_CONFIRMATION_EMAIL_SUCCESS",
  SEND_EMAILID_CONFIRMATION_EMAIL_ERROR:
    "SEND_EMAILID_CONFIRMATION_EMAIL_ERROR",

  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",

  LOGIN_WITH_GOOGLE: "LOGIN_WITH_GOOGLE",
  LOGIN_WITH_GOOGLE_SUCCESS: "LOGIN_WITH_GOOGLE_SUCCESS",
  LOGIN_WITH_GOOGLE_ERROR: "LOGIN_WITH_GOOGLE_ERROR",

  LOGOUT: "LOGOUT",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_ERROR: "LOGOUT_ERROR",

  SEND_FORGOT_PASSWORD_MAIL: "SEND_FORGOT_PASSWORD_MAIL",
  SEND_FORGOT_PASSWORD_MAIL_SUCCESS: "SEND_FORGOT_PASSWORD_MAIL_SUCCESS",
  SEND_FORGOT_PASSWORD_MAIL_ERROR: "SEND_FORGOT_PASSWORD_MAIL_EVENT_ERROR",

  MAKE_USER_PREMIUM: "MAKE_USER_PREMIUM",
  MAKE_USER_PREMIUM_SUCCESS: "MAKE_USER_PREMIUM_SUCCESS",
  MAKE_USER_PREMIUM_ERROR: "MAKE_USER_PREMIUM_ERROR",

  MAKE_USER_NORMAL: "MAKE_USER_NORMAL",
  MAKE_USER_NORMAL_SUCCESS: "MAKE_USER_NORMAL_SUCCESS",
  MAKE_USER_NORMAL_ERROR: "MAKE_USER_NORMAL_ERROR",

  BACKUP: "BACKUP",
  BACKUP_SUCCESS: "BACKUP_SUCCESS",
  BACKUP_ERROR: "BACKUP_ERROR",

  RESTORE: "RESTORE",
  RESTORE_SUCCESS: "RESTORE_SUCCESS",
  RESTORE_ERROR: "RESTORE_ERROR",

  FETCH_USER: "FETCH_USER",
  FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
  FETCH_USER_ERROR: "FETCH_USER_ERROR",

  FETCH_USER_LOCAL_DATA: "FETCH_USER_LOCAL_DATA",
  FETCH_USER_LOCAL_DATA_SUCCESS: "FETCH_USER_LOCAL_DATA_SUCCESS",
  FETCH_USER_LOCAL_DATA_ERROR: "FETCH_USER_LOCAL_DATA_ERROR",

  SAVE_USER_LOCAL_DATA: "SAVE_USER_LOCAL_DATA",
  SAVE_USER_LOCAL_DATA_SUCCESS: "SAVE_USER_LOCAL_DATA_SUCCESS",
  SAVE_USER_LOCAL_DATA_ERROR: "SAVE_USER_LOCAL_DATA_ERROR",

  CHECK_LOGIN_ERROR_REASON: "CHECK_LOGIN_ERROR_REASON",
  CHECK_LOGIN_ERROR_REASON_SUCCESS: "CHECK_LOGIN_ERROR_REASON_SUCCESS",
  CHECK_LOGIN_ERROR_REASON_ERROR: "CHECK_LOGIN_ERROR_REASON_ERROR",

  // internally generated events
  USER_STATE_FETCH: "USER_STATE_FETCH",
  USER_STATE_FETCH_SUCCESS: "USER_STATE_FETCH_SUCCESS",
  USER_STATE_FETCH_ERROR: "USER_STATE_FETCH_ERROR",

  UPDATE_USER_DETAILS: "UPDATE_USER_DETAILS",
  UPDATE_USER_DETAILS_SUCCESS: "UPDATE_USER_DETAILS_SUCCESS",
  UPDATE_USER_DETAILS_ERROR: "UPDATE_USER_DETAILS_ERROR",

  //GLOBAL EVENTS
  DOCUMENT_CLICK_ON_LINK: "DOCUMENT_CLICK_ON_LINK",
  UNLINK: "UNLINK",
  NOTIFICATION_WITH_CROSS: "NOTIFICATION_WITH_CROSS",
  ANNOUNCEMENT_WITH_CROSS: "ANNOUNCEMENT_WITH_CROSS",
  FULL_CLOSABLE_NOTIFICATION: "FULL_CLOSABLE_NOTIFICATION",
  BLOCKED_LOADING: "BLOCKED_LOADING",
  ASK_FOR_CONSENT: "ASK_FOR_CONSENT",
  WAKEUP_FIRESTORE: "WAKEUP_FIRESTORE",
  WAKEUP_FIRESTORE_SUCCESS: "WAKEUP_FIRESTORE_SUCCESS",
  WAKEUP_FIRESTORE_ERROR: "WAKEUP_FIRESTORE_ERROR",
  WAKEUP_USER_EMPTY: "WAKEUP_USER_EMPTY",
  USER_AUTO_LOGOUT: "USER_AUTO_LOGOUT",
  FORCE_LOGIN: "FORCE_LOGIN",

  //*** Backup restore events **/
  SHOW_RESTORE_HELPER_OVERLAY_FOLDER_ID:
    "SHOW_RESTORE_HELPER_OVERLAY_FOLDER_ID",
  RATING_CLICK: "RATING_CLICK",
  RATING_CLOSED: "RATING_CLOSED",
  RATING_NOTIFICATION: "RATING_NOTIFICATION",
  LIKE_BUTTON_CLICK: "LIKE_BUTTON_CLICK",
  DISLIKE_BUTTON_CLICK: "DISLIKE_BUTTON_CLICK",
  LIKEDISLIKE_NOTIFICATION_CLICK: "LIKEDISLIKE_NOTIFICATION_CLICK",
  LIKEDISLIKE_DATA_SENT: "LIKEDISLIKE_DATA_SENT",
  SEE_VIDEO: "SEE_VIDEO",
  EMAIL_UNVERIFIED_POPUP_CLICK: "EMAIL_UNVERIFIED_POPUP_CLICK",
  OLDDATA_LINK: "OLDDATA_LINK",
  OLDDATA_LINK_SEEN: "OLDDATA_LINK_SEEN",

  AUTONOTE_FEATURES_SHOW: "AUTONOTE_FEATURES_SHOW",
  AUTOOPEN_SETTINGS: "AUTOOPEN_SETTINGS",
  SHOULD_RESET_NOTES_TO_FOLDER1: "SHOULD_RESET_NOTES_TO_FOLDER1",
  RESET_NOTES_TO_FOLDER1_DONE: "RESET_NOTES_TO_FOLDER1_DONE",
  NEVER_SHOW_AGAIN_ZOOM_POPUP: "NEVER_SHOW_AGAIN_ZOOM_POPUP",
  INSTALL_ERROR_WHITE_PAGE_NO_LOCAL_DATA:
    "INSTALL_ERROR_WHITE_PAGE_NO_LOCAL_DATA",
  INSTALL_ERROR_WHITE_PAGE_NO_LOCAL_DATA_BUTTON_CLICK:
    "INSTALL_ERROR_WHITE_PAGE_NO_LOCAL_DATA_BUTTON_CLICK",
  INSTALL_ERROR_WHITE_PAGE_LOCAL_DATA_PRESENT:
    "INSTALL_ERROR_WHITE_PAGE_LOCAL_DATA_PRESENT",
  INSTALL_ERROR_WHITE_PAGE_LOCAL_DATA_PRESENT_BUTTON_CLICK:
    "INSTALL_ERROR_WHITE_PAGE_LOCAL_DATA_PRESENT_BUTTON_CLICK",
  INSTALL_ERROR_WHITE_PAGE_LOCAL_DATA_ABSENT_BUTTON_CLICK:
    "INSTALL_ERROR_WHITE_PAGE_LOCAL_DATA_ABSENT_BUTTON_CLICK",
  WHITE_PAGE_INDEXDB_BLOCKED: "WHITE_PAGE_INDEXDB_BLOCKED",

  SUBMIT_FEEDBACK: "SUBMIT_FEEDBACK",
  SUBMIT_FEEDBACK_SUCCESS: "SUBMIT_FEEDBACK_SUCCESS",
  SUBMIT_FEEDBACK_ERROR: "SUBMIT_FEEDBACK_ERROR",

  //****************EVENTS***********************************

  COUNT_BUCKET: [
    1, 2, 5, 10, 15, 20, 30, 40, 50, 75, 100, 150, 250, 400, 800, 1000, 2000,
    5000, 10000, 20000, 30000, 50000, 80000,
  ],
  SECONDS_BUCKET: [
    2, 4, 6, 10, 20, 40, 60, 100, 200, 300, 400, 500, 600, 700, 800, 1000, 1500,
    2000, 3600, 7200, 14400,
  ],

  NOTE_ACTIVITY: "NOTE_ACTIVITY",
  FOLDER_ACTIVITY: "FOLDER_ACTIVITY",
  RICH_TEXT_ACTIVITY: "RICH_TEXT_ACTIVITY",
  SETTINGS_ACTIVITY: "SETTINGS_ACTIVITY",
  PREMIUM_THEMES_ACTIVITY: "PREMIUM_THEMES_ACTIVITY",
  BACKUP_ACTIVITY: "BACKUP_ACTIVITY",
  WAIT_ACTIVITY: "WAIT_ACTIVITY",
  DOWNLOAD_ACTIVITY: "DOWNLOAD_ACTIVITY",
  TYPE_TIME_RATIO_ACTIVITY: "TYPE_TIME_RATIO_ACTIVITY",
  SECONDARY_BACKUP_AT_COUNT: "SECONDARY_BACKUP_AT_COUNT",

  FOLDER_ACTIVITY_THRESHOLDS: {
    LOW: 20,
    MEDIUM: 50,
    HIGH: 100,
  },

  RICH_TEXT_ACTIVITY_THRESHOLDS: {
    LOW: 20,
    MEDIUM: 50,
    HIGH: 100,
  },

  SETTINGS_ACTIVITY_THRESHOLDS: {
    LOW: 20,
    MEDIUM: 50,
    HIGH: 100,
  },

  PREMIUM_THEMES_ACTIVITY_THRESHOLDS: {
    LOW: 5,
    MEDIUM: 10,
    HIGH: 20,
  },

  BACKUP_ACTIVITY_THRESHOLDS: {
    LOW: 3,
    MEDIUM: 8,
    HIGH: 15,
  },

  WAIT_ACTIVITY_THRESHOLDS: {
    LOW: 20,
    MEDIUM: 50,
    HIGH: 100,
  },
  DOWNLOAD_ACTIVITY_THRESHOLDS: {
    LOW: 10,
    MEDIUM: 20,
    HIGH: 50,
  },

  // GA Categories

  APP_OPEN: "APP_OPEN",
  USAGE: "USAGE",
  FOLDER: "FOLDER",
  SETTINGS: "SETTINGS",
  NOTES: "NOTES",
  NOTIFICATION: "NOTIFICATION",
  FIXED_BUTTON: "FIXED_BUTTON",
  AUTH: "AUTH",
  ONINSTALLPAGE: "ONINSTALLPAGE",
  DOWNLOADPAGE: "DOWNLOADPAGE",
  RESTORE_DATA_PAGE: "RESTORE_DATA_PAGE",
  LICENSE_BUY: "LICENSE_BUY",
  BEHAVIOUR: "BEHAVIOUR",
  SHOW_LOGIN_OVERLAY: "SHOW_LOGIN_OVERLAY",

  // value
  POPUP_CLOSE: "POPUP_CLOSE",
  POPUP_TAB_CLOSE: "POPUP_TAB_CLOSE",
  APP_OPEN_IN_TAB: "APP_OPEN_IN_TAB",
  APP_OPEN_IN_POPUP: "APP_OPEN_IN_POPUP",
  POPUP_LAST_OPEN_DATE: "LAST_OPEN_DATE",
  POPUP_OPEN_DAYS_COUNT: "POPUP_OPEN_DAYS_COUNT",
  POPUP_OPEN_COUNT: "POPUP_OPEN_COUNT",
  OFFLINE_COUNT_WHEN_POPUP_OPEN: "OFFLINE_COUNT_WHEN_POPUP_OPEN",
  INSTALLED: "INSTALLED",
  SYNCDATA_KEY: "SYNCDATA_KEY",
  SYNC_DATA_WAITING_TO_SEND: "SYNC_DATA_WAITING_TO_SEND",
  RESTORE_DATA_PAGE_OPEN: "RESTORE_DATA_PAGE_OPEN",
  RESTORE_DATA_PAGE_OPEN_FROM_INSTALL_ERROR_PAGE:
    "RESTORE_DATA_PAGE_OPEN_FROM_INSTALL_ERROR_PAGE",
  RESTORE_DATA_PAGE_OPEN_FROM_FIXED_BUTTON:
    "RESTORE_DATA_PAGE_OPEN_FROM_FIXED_BUTTON",

  THEME_CORONA_HIGHSCORE: "THEME_CORONA_HIGHSCORE",
  THEME_SNOW_SUBTHEME: "THEME_SNOW_SUBTHEME",

  //Install
  INSTALLATION: "INSTALLATION",
  APP_INSTALL_PAGE_OPEN: "APP_INSTALL_PAGE_OPEN",
  APP_INSTALL_SUCCESS_FULL: "APP_INSTALL_SUCCESS_FULL",
  APP_MIGRATED: "APP_MIGRATED",
  APP_UPDATED: "APP_UPDATED",

  //license
  LICENSE_BUY_BUTTON_CLICK: "LICENSE_BUY_BUTTON_CLICK",

  // Folder ----------------------------------------

  CLICK_FOLDER: "CLICK_FOLDER",
  OPEN_FOLDER_DROPDOWN: "OPEN_FOLDER_DROPDOWN",
  FOLDER_DROPDOWN_SMALL_NOTE_CLICK: "FOLDER_DROPDOWN_SMALL_NOTE_CLICK",
  FOLDER_NAME_CHANGE: "FOLDER_NAME_CHANGE",
  FOLDER_OPEN_COUNT: "FOLDER_OPEN_COUNT",

  //Settings------------------------------------------

  OPEN_IN_TAB: "OPEN_IN_TAB",
  FOCUS_MODE: "FOCUS_MODE",
  FOCUS_MODE_LSCHECK: "FOCUS_MODE_LSCHECK",

  MENU_OPEN: "MENU_OPEN",
  MENU_CLOSE_MANUALLY: "MENU_CLOSE_MANUALLY",

  SKIPPABLE_LOGIN_CLICK: "SKIPPABLE_LOGIN_CLICK",
  SKIP_BUTTON_CLICK: "SKIP_BUTTON_CLICK",

  LOGIN_BUTTON_CLICK: "LOGIN_BUTTON_CLICK",
  UPGRADE_BUTTON_CLICK: "LOGIN_BUTTON_CLICK",
  LOGOUT_BUTTON_CLICK: "LOGOUT_BUTTON_CLICK",

  CLICK_BACKUP: "CLICK_BACKUP",

  NOTE_SIZE_DROPDOWN_CLICK: "NOTE_SIZE_DROPDOWN_CLICK",
  FONT_FAMILY_DROPDOWN_CLICK: "FONT_FAMILY_DROPDOWN_CLICK",
  FONT_SIZE_DROPDOWN_CLICK: "FONT_SIZE_DROPDOWN_CLICK",
  THEME_DROPDOWN_CLICK: "THEME_DROPDOWN_CLICK",

  PREMIUM_THEME_CLICK: "PREMIUM_THEME_CLICK",
  SETTINGS_PROPERTY_CHANGE: "SETTINGS_PROPERTY_CHANGE",

  MENU_FACEBOOK_CLICK: "MENU_FACEBOOK_CLICK",
  MENU_TWITTER_CLICK: "MENU_TWITTER_CLICK",
  HELP_SECTION_CLICK: "HELP_SECTION_CLICK",
  HELP_CLOSED_AFTER_FAQ_SCROLL: "HELP_CLOSED_AFTER_FAQ_SCROLL",
  LOVE_SECTION_CLICK: "LOVE_SECTION_CLICK",

  EMAIL_COPY_CLICK: "EMAIL_COPY_CLICK",
  EMAIL_BUTTON_CLICK: "EMAIL_BUTTON_CLICK",

  RATE_BUTTON_CLICK: "RATE_BUTTON_CLICK",
  LOVE_SECTION_FACEBOOK_CLICK: "LOVE_SECTION_FACEBOOK_CLICK",
  LOVE_SECTION_TWITTER_CLICK: "LOVE_SECTION_TWITTER_CLICK",

  BACKUP_OPTION_CHANGE: "BACKUP_OPTION_CHANGE",
  BACKUP_OPTIONS_CLICK: "BACKUP_OPTIONS_CLICK",

  EASTER_FIRST_MOUNTAIN_CLICK: "EASTER_FIRST_MOUNTAIN_CLICK",
  EASTER_FIRST_MOON_CLICK: "EASTER_FIRST_MOON_CLICK",

  // Note----------------------------------

  SMALL_NOTE_TAB_CLICK: "SMALL_NOTE_TAB_CLICK",

  NOTE_MENU_OPEN: "NOTE_MENU_OPEN",
  DOWNLOAD_NOTE_CLICK: "DOWNLOAD_NOTE_CLICK",
  PRINT_NOTE_CLICK: "PRINT_NOTE_CLICK",
  CLEAR_NOTE_CLICK: "CLEAR_NOTE_CLICK",
  HIDE_NOTE_CLICK: "HIDE_NOTE_CLICK",

  WAIT_AND_CLICK: "WAIT_AND_CLICK",

  CLICK_LOADER_BUTTON: "CLICK_LOADER_BUTTON",

  RICH_TEXT_KEYBOARD_SHORTCUT_CLICK: "RICH_TEXT_KEYBOARD_SHORTCUT_CLICK",
  RICH_TEXT_ACTIONBAR_CLICK: "RICH_TEXT_ACTIONBAR_CLICK",

  CREATE_LINK_FROM_SELECTION_DONE_CLICK:
    "CREATE_LINK_FROM_SELECTION_DONE_CLICK",

  LINK_EDITOR_LINK_CLICK: "LINK_EDITOR_LINK_CLICK",
  LINK_EDITOR_UNLINK_CLICK: "LINK_EDITOR_UNLINK_CLICK",
  LINK_EDITOR_DONE_CLICK: "LINK_EDITOR_DONE_CLICK",
  LINK_EDITOR_EDIT_CLICK: "LINK_EDITOR_EDIT_CLICK",

  PASTE_ON_NOTE: "PASTE_ON_NOTE",
  COPY_FROM_NOTE: "COPY_FROM_NOTE",

  //*other

  FIXED_BUTTON_CLICK: "FIXED_BUTTON_CLICK",

  MANUALLY_CLOSE_NOTIFICATION: "MANUALLY_CLOSE_NOTIFICATION",

  //Auth
  AUTH_PAGE_OPEN: "AUTH_PAGE_OPEN",
  GOOGLE_LOGIN_BUTTON_CLICK: "GOOGLE_LOGIN_BUTTON_CLICK",
  LOGIN_WITH_EMAIL_BUTTON_CLICK: "LOGIN_SIGNUP_BUTTON_CLICK",
  CREATE_ACCOUNT_SUBMIT_BUTTON: "CREATE_ACCOUNT_SUBMIT_BUTTON",
  RESET_PASSWORD_CLICK: "RESET_PASSWORD_CLICK",
  RESET_PASSWORD_EMAIL_SUBMIT_CLICK: "RESET_PASSWORD_EMAIL_SUBMIT_CLICK",
  LICENSE_SUBMIT_BUTTON_CLICK: "LICENSE_SUBMIT_BUTTON_CLICK",
  BUY_LICENSE_BUTTON_CLICK: "BUY_LICENSE_BUTTON_CLICK",
  AUTH_BACKUP_OPTION_SELECTED: "AUTH_BACKUP_OPTION_SELECTED",

  //other
  CLICK_EVENTS: "CLICK_EVENTS",
  PASTE_EVENTS: "PASTE_EVENTS",
  KEY_UP_EVENTS: "KEY_UP_EVENTS",
  TOTAL_APP_OPEN_TIME_SECONDS: "TOTAL_APP_OPEN_TIME_SECONDS",

  //typing
  TOTAL_TYPING_BURST_COUNT: "TOTAL_TYPING_BURST_COUNT",
  TOTAL_TYPING_TIME_COUNT: "TOTAL_TYPING_TIME_COUNT",
  APP_OPEN_DIVIDEBY_TYPING_COUNT: "APP_OPEN_DIVIDE_BY_TYPING_COUNT",

  //Install Page
  BUY_LICENSE_ON_INSTALL_PAGE_CLICK: "BUY_LICENSE_ON_INSTALL_PAGE_CLICK",
  INSTALL_PAGE_OPTION_1: "INSTALL_PAGE_OPTION_1",
  INSTALL_PAGE_OPTION_2: "INSTALL_PAGE_OPTION_2",
  INSTALL_PAGE_OPTION_3: "INSTALL_PAGE_OPTION_3",

  //Download Page
  DOWNLOAD_AS_TEXT_CLICK: "DOWNLOAD_AS_TEXT_CLICK",
  PRINT_BUTTON_CLICK: "PRINT_BUTTON_CLICK",
};

// this.props.logToAmplitude(COMMONCONSTANTS.RESET_PASSWORD_CLICK);
// TRACK({
// 	category: COMMONCONSTANTS.AUTH,
// 	action:COMMONCONSTANTS.RESET_PASSWORD_CLICK,
// });
